name: test-apps
base: core18
version: '0.1'
summary: Snapcraft demo for apps
description: |
  Simple snap to exercise snapcraft apps

grade: stable 
confinement: strict

apps:
  test-apps:
    command: test-apps.sh
  hello:
    command: hello.sh
  adaemon:
    command: adaemon.sh
    daemon: simple
    after:
      - oneshotdaemon
  oneshotdaemon:
    command: oneshotdaemon.sh
    daemon: oneshot

parts:
  test-apps:
    source: test-apps
    plugin: dump
  hello:
    source: hello
    plugin: dump
  adaemon:
    source: adaemon
    plugin: dump
  oneshotdaemon:
    source: oneshotdaemon
    plugin: dump

